### ISSUE TITLE
Review URL

### ISSUE THREAD

**Issue by RichardShea** [cetiny/awesome-taleb#4]
This URL doesn't lead me to the reviews:

Nassim Taleb leaves [reviews](https://www.amazon.com/gp/profile/amzn1.account.AHMHNR4MRTDLMBOOT6Q7LX2WP5YA/ref=cm_cr_dp_d_gw_tr?ie=UTF12) for his favorite books on Amazon.

**Comment by cetiny** [comment]
Thank you. It seems that he or Amazon removed it. I have removed the hyperlink from the list.
